export var products = [
   {"id": "1",
      "color": "lime",
      "department": "Music",
      "productName": "Sleek Wooden Table",
      "price": "331.00",
      "productAdjective": "Licensed",
      "productMaterial": "Steel",
      "product": "Computer",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "2",
      "color": "cyan",
      "department": "Sports",
      "productName": "Generic Wooden Pizza",
      "price": "413.00",
      "productAdjective": "Practical",
      "productMaterial": "Cotton",
      "product": "Salad",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "3",
      "color": "lavender",
      "department": "Tools",
      "productName": "Ergonomic Soft Keyboard",
      "price": "710.00",
      "productAdjective": "Gorgeous",
      "productMaterial": "Fresh",
      "product": "Chips",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "4",
      "color": "white",
      "department": "Books",
      "productName": "Incredible Concrete Hat",
      "price": "514.00",
      "productAdjective": "Small",
      "productMaterial": "Concrete",
      "product": "Chicken",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "5",
      "color": "azure",
      "department": "Grocery",
      "productName": "Generic Plastic Gloves",
      "price": "474.00",
      "productAdjective": "Handmade",
      "productMaterial": "Rubber",
      "product": "Chips",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "6",
      "color": "gold",
      "department": "Industrial",
      "productName": "Fantastic Cotton Mouse",
      "price": "520.00",
      "productAdjective": "Licensed",
      "productMaterial": "Plastic",
      "product": "Fish",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "7",
      "color": "gold",
      "department": "Tools",
      "productName": "Gorgeous Metal Chips",
      "price": "20.00",
      "productAdjective": "Ergonomic",
      "productMaterial": "Cotton",
      "product": "Sausages",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "8",
      "color": "cyan",
      "department": "Beauty",
      "productName": "Unbranded Frozen Chair",
      "price": "307.00",
      "productAdjective": "Unbranded",
      "productMaterial": "Metal",
      "product": "Gloves",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "9",
      "color": "plum",
      "department": "Automotive",
      "productName": "Small Rubber Car",
      "price": "885.00",
      "productAdjective": "Intelligent",
      "productMaterial": "Soft",
      "product": "Keyboard",
      "image": "iphone-14-pro.jpg"
    },
    {"id": "10",
      "color": "olive",
      "department": "Jewelery",
      "productName": "Sleek Fresh Car",
      "price": "591.00",
      "productAdjective": "Small",
      "productMaterial": "Concrete",
      "product": "Chicken",
      "image": "iphone-14-pro.jpg"
    }
  ]